// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    DateTime: typeof import('./../components/DateTime/index.vue')['default']
    MemberDetail: typeof import('./../components/MemberDetail/index.vue')['default']
    RoomDetail: typeof import('./../components/RoomDetail/index.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SvgIcon: typeof import('./../components/SvgIcon/index.vue')['default']
    Time: typeof import('./../components/Time/index.vue')['default']
  }
}
